name: Rust CI

on:
  pull_request:
    paths:
      - "sdks/rust/**"
      - ".github/workflows/ci-rust.yml"
  push:
    branches: [main]
    paths:
      - "sdks/rust/**"
      - ".github/workflows/ci-rust.yml"

jobs:
  rust:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --all-features --all-targets -- -D warnings
      - name: Cargo test
        run: cargo test --all-features

  rust-msrv-no-features:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: sdks/rust
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.82.0
      - name: Cargo build (no features)
        run: cargo build
      - name: Cargo test (no features)
        run: cargo test
